
spring.Data.mongodb.uri="mongodb+srv://Cesarandresrl08:AzG7YQdZUx7iG8d@cluster0.ofvze1d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
spring.mongodb.database=db_security
server.port=8081
jwt.secret=carl
jwt.expiration=3600000